/** Transcribed from the in-house "Fine Dining Menu" PDF. Prices in INR; 10% service charge and government tax extra. */
export type Diet = "veg" | "nonveg" | "both" | "none";
export type Dish = { name: string; note?: string; price: string; diet: Diet; signature?: boolean };
export type MenuSection = { id: string; title: string; subtitle?: string; dishes: Dish[] };

const d = (name: string, price: string, diet: Diet, note?: string, signature?: boolean): Dish => ({ name, price, diet, note, signature });

export const menu: MenuSection[] = [
  {
    id: "breakfast",
    title: "Breakfast",
    subtitle: "Served 07:00 – 10:00",
    dishes: [
      d("The American Breakfast", "449", "nonveg", "Eggs scrambled or poached, chicken sausage, potato wedges or hash brown, white/brown bread with jam, marmalade & honey, fresh cut fruit, fresh juice, tea or coffee."),
      d("The Continental Breakfast", "399", "veg", "White/brown bread with jam, jelly, marmalade & honey, fresh cut fruit, fresh juice, tea or coffee."),
      d("The Indian Breakfast", "399", "veg", "Poori bhaji, chole bhature or aloo paratha with curd and pickle. Chef's special kheer, fresh juice, tea or coffee."),
      d("Assamese Jolpan", "349", "veg", "Luchi with bhaji, fresh cut fruit, chira or muri with milk or curd, fresh juice, tea or coffee.", true),
      d("Idli", "299", "veg", "Steamed rice and lentil cakes with sambar and chutney."),
      d("Dosa", "299", "veg", "Masala, plain or onion — crisp rice & lentil pancake with sambar and chutney."),
      d("Poori Bhaji", "249", "veg", "Served with potato curry."),
      d("Masala Poha", "299", "veg", "Spiced flattened rice tossed with onions, peanuts and aromatic Indian spices."),
      d("Paratha", "249", "veg", "Aloo, gobi or masala — griddled stuffed flatbread with yogurt and pickle."),
      d("Two Eggs Your Own Way", "199", "nonveg", "Masala, plain, cheese or poached."),
      d("Bread Toast", "149", "veg", "White or brown, served with jam and butter."),
    ],
  },
  {
    id: "soup-salad",
    title: "Soups & Salads",
    dishes: [
      d("Blossom Special Manimuni Soup", "249", "veg", "A soothing, aromatic herbal soup of fresh mani muni leaves — light, healthy nourishment.", true),
      d("Cream of Tomato", "249", "veg", "Ripe tomatoes and fresh cream, velvety and comforting."),
      d("Manchow Soup", "249 / 299", "both", "Veg / Chicken — spicy, tangy Indo-Chinese soup topped with crispy noodles."),
      d("Lemon Coriander", "249 / 299 / 349", "both", "Veg / Chicken / Prawn — citrusy and bright with fresh coriander."),
      d("Tom Yum", "249 / 299 / 349", "both", "Veg / Chicken / Prawn — lemongrass, lime and fresh coriander."),
      d("Paya Shorba", "349", "nonveg", "Slow-cooked trotter broth with warming spices."),
      d("Fresh Garden Green Salad", "199", "veg"),
      d("Raw Papaya Salad", "249", "veg", "Shredded papaya, herbs and a tangy dressing."),
      d("Caesar Salad", "249 / 299", "both", "Veg / Non-veg — crisp lettuce, creamy dressing, parmesan and croutons."),
      d("Prawn Quinoa Salad", "399", "nonveg", "Juicy prawns, fluffy quinoa and fresh vegetables in a light dressing."),
    ],
  },
  {
    id: "small-plates",
    title: "Small Plates",
    dishes: [
      d("Tomato & Basil Bruschetta", "249", "veg", "Toasted bread, fresh tomato, basil and olive oil."),
      d("Peanut Masala", "199", "veg", "Roasted peanuts with onion, tomato and masala."),
      d("Garlic Bread", "199", "veg", "Butter, garlic and herbs, toasted crisp."),
      d("French Fries", "249", "veg", "Peri peri or cheesy."),
      d("Chilli Cheese Toast", "199", "veg", "Melted cheese with a spicy chilli kick."),
      d("Chicken Popcorn", "299", "nonveg", "Bite-sized, crunchy fried chicken."),
      d("Masala Papad", "149", "veg"),
    ],
  },
  {
    id: "starters",
    title: "Starters & Tandoor",
    dishes: [
      d("Blossom Special Veg Tandoori Platter", "699", "veg", "Paneer tikka, malai broccoli, sweet potato, hara bhara kebab and tandoori pineapple.", true),
      d("Blossom Special Non-Veg Tandoori Platter", "999", "nonveg", "Tandoori chicken, chicken malai tikka, mutton kebab, tandoori prawn and fish tikka.", true),
      d("Paneer Tikka", "399", "veg", "Achari, malai or hariyali — grilled to smoky perfection."),
      d("Jacket Potato", "399", "veg", "Fluffy baked potato loaded with savoury toppings."),
      d("Hara Bhara Kebab", "399", "veg", "Spinach and green vegetable patties, pan-fried golden."),
      d("Dahi Ke Kebab", "399", "veg", "Soft, creamy yogurt patties, lightly spiced."),
      d("Crispy American Corn", "349", "veg", "Golden corn with a sharp salt-and-pepper kick."),
      d("Kamal Kakdi Fire", "399", "veg", "Crispy lotus stem in a sweet and spicy honey-chilli glaze."),
      d("Chilli Paneer", "399", "veg", "Paneer, peppers and fiery chilli seasoning."),
      d("Wings Your Own Way", "449", "nonveg", "BBQ, Bhoot Jolokia, hot garlic or mambo."),
      d("Fish Finger", "449", "nonveg", "Golden fish strips in a crisp coating."),
      d("Choice of Chicken Tikka", "449", "nonveg", "Achari, malai, Afghani or kalimirchi."),
      d("Choice of Fish Tikka", "449", "nonveg", "Achari or hariyali."),
      d("Tandoori Chicken", "449 / 799", "nonveg", "Half / Full."),
      d("Chilli Chicken", "449", "nonveg", "Fiery, crispy and saucy."),
      d("Galouti G.O.A.T.", "599", "nonveg", "Melt-in-the-mouth mutton kebabs with royal Awadhi spices.", true),
      d("Smoked Pork", "499", "nonveg", "Rich, tender and deeply smoky."),
      d("Prawn Tempura", "599", "nonveg", "Light, crisp, golden."),
      d("Flame Kiss Tandoori Prawn", "599", "nonveg", "Prawns kissed by the flame, bursting with tandoori spice."),
      d("Charcoal Grilled Pomfret", "699", "nonveg", "Tandoori-marinated and char-grilled."),
      d("The Golden Ring of the Sea", "699", "nonveg", "Golden, crunchy calamari rings."),
    ],
  },
  {
    id: "mains",
    title: "Main Course",
    dishes: [
      d("Paneer Your Own Way", "449", "veg", "Butter masala, lababdar, makhani, palak, tikka masala, shahi or khurchan."),
      d("Mushroom Hara Pyaaz", "449", "veg", "Mushrooms and spring onion in a light, aromatic curry."),
      d("Okra Do Pyaza", "399", "veg", "Crisp bhindi tossed with double onions."),
      d("Kashmiri Dum Aloo", "399", "veg", "Baby potatoes in a velvety Kashmiri-spiced gravy."),
      d("Tawa Subz", "399", "veg", "Seasonal vegetables seared on a hot tawa."),
      d("Corn Palak", "399", "veg", "Sweet corn in a creamy spinach sauce."),
      d("Malai Kofta", "449", "veg", "Soft koftas in an aromatic cream gravy."),
      d("Chicken Your Own Way", "499", "nonveg", "Tikka masala, butter masala or lababdar."),
      d("Fish Your Own Way", "499", "nonveg", "Fish tenga, fish kalia or fish curry."),
      d("Bhuna Gosht", "599", "nonveg", "Slow-cooked meat in a thick, intensely spiced masala."),
      d("Mutton Rogan Josh", "599", "nonveg", "Succulent mutton in an aromatic Kashmiri curry."),
      d("Mutton Korma", "599", "nonveg", "Tender mutton in a creamy nut-and-spice gravy."),
      d("Laal Maas", "599", "nonveg", "Fiery Rajasthani mutton curry with bold red chillies."),
      d("Prawn Masala", "649", "nonveg", "Prawns in a rich tomato-onion gravy."),
      d("Malabar Prawn Curry", "649", "nonveg", "Coastal comfort — creamy, spicy and aromatic."),
      d("Naga Chicken", "499", "nonveg", "Simple, fiery and full of authentic tribal flavour.", true),
      d("Yellow Dal Tadka", "299", "veg", "A classic, heart-warming tempered dal."),
      d("Dal Makhani", "349", "veg", "Black lentils and kidney beans slow-cooked with butter and cream."),
      d("Dal Panchmel", "349", "veg", "Five lentils simmered together, Rajasthani style."),
    ],
  },
  {
    id: "world",
    title: "Around the World & Asian",
    dishes: [
      d("Pasta Your Own Way", "399 / 449", "both", "Penne or spaghetti · alfredo, arrabbiata or pesto."),
      d("Spaghetti Aglio Olio", "399 / 449", "both", "Veg / Non-veg."),
      d("Thai Curry", "399 / 449 / 549", "both", "Red or green · Veg / Chicken / Prawn."),
      d("Stir-Fried Noodles", "349 / 399 / 449 / 499", "both", "Veg / Egg / Chicken / Mixed."),
      d("Fried Rice", "349 / 399 / 449 / 499", "both", "Veg / Egg / Chicken / Mixed."),
      d("Schezwan Fried Rice", "349 / 399 / 449 / 499", "both", "Veg / Egg / Chicken / Mixed."),
      d("Veg Manchurian", "399", "veg", "Crispy vegetable balls in a bold, tangy sauce."),
      d("Stir-Fried Vegetables", "399", "veg", "Garlic, hot garlic or Hunan sauce."),
      d("Mushroom with Choice of Sauce", "449", "veg", "Garlic, hot garlic or Hunan."),
      d("Kung Pao Chicken", "499", "nonveg", "Chicken with crunchy peanuts and a spicy-sweet punch."),
      d("Chicken with Choice of Sauce", "449", "nonveg", "Garlic, hot garlic, Hunan or black bean."),
      d("Fish with Choice of Sauce", "499", "nonveg", "Garlic, hot garlic or oyster."),
      d("Prawn with Choice of Sauce", "649", "nonveg", "Garlic, hot garlic or chilli garlic."),
      d("Pork with Choice of Sauce", "549", "nonveg", "BBQ, hoisin, plum or chilli with bamboo shoots."),
      d("Sliced Pork with Chilli Basil", "549", "nonveg", "Glazed in a fiery, aromatic basil sauce."),
    ],
  },
  {
    id: "rice-breads",
    title: "Rice, Breads & Sides",
    dishes: [
      d("Biryani", "349 / 399 / 499", "both", "Veg / Chicken / Mutton."),
      d("Veg Pulao", "349", "veg"),
      d("Jeera Rice", "299", "veg"),
      d("Jasmine Rice", "299", "veg"),
      d("Steamed Rice", "249", "veg"),
      d("Tandoori Roti", "69", "none"),
      d("Naan", "79 / 89 / 99", "none", "Plain / Butter / Garlic."),
      d("Kulcha", "89 / 99 / 119", "none", "Plain / Onion / Masala."),
      d("Lachha Paratha", "99", "none"),
      d("Tawa Roti", "69", "none"),
      d("Rumali Roti", "99", "none"),
      d("Raita", "199", "veg", "Mixed veg, boondi, onion or masala."),
      d("Plain Curd", "149", "veg"),
      d("Papad", "99", "veg", "Roasted or fried."),
    ],
  },
  {
    id: "sweets-drinks",
    title: "Desserts & Beverages",
    dishes: [
      d("Gulab Jamun", "199", "none"),
      d("Caramel Custard", "249", "none", "Silky custard under a golden caramel."),
      d("Black Rice Kheer", "199", "none", "Creamy, nutty and subtly sweet — a regional classic, reimagined.", true),
      d("Choice of Ice Cream", "149", "none", "Vanilla, chocolate, strawberry or butterscotch."),
      d("Milkshake", "249", "none", "Vanilla, chocolate or strawberry."),
      d("Lassi", "249", "none"),
      d("Fresh Fruit Juice", "249", "none"),
      d("Fresh Lime Soda / Water", "199", "none"),
      d("Tea / Coffee", "199", "none"),
      d("Assam Tea", "149", "none"),
      d("Green Tea", "149", "none"),
      d("Coke / Sprite", "199", "none"),
      d("Red Bull", "249", "none"),
      d("Canned Juice", "149", "none"),
      d("Packaged Drinking Water", "149", "none"),
    ],
  },
];
