import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Archive, ArrowLeft, ArrowRight, BellRing, Check, ChevronRight, CircleAlert, Clock3, IndianRupee, LayoutDashboard, LogOut, Menu, NotebookPen, RefreshCw, SlidersHorizontal, UsersRound, X } from "lucide-react";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { api, configured, type Inquiry, type InquiryDetail, type InquiryStatus, type Rate, type StaffMember, type Summary, supabase } from "../lib/staff-api";

type View = "overview" | "inquiries" | "rates";
const statuses: InquiryStatus[] = ["new", "contacted", "provisional", "confirmed", "cancelled", "closed"];
const statusTone = (status: InquiryStatus) => status;
const readable = (value: string) => value.replaceAll("_", " ");
const compactDate = (value?: string | null) => value ? new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "—";
const dateTime = (value?: string | null) => value ? new Intl.DateTimeFormat("en-IN", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "No follow-up set";
const localInput = (value?: string | null) => value ? new Date(value).toISOString().slice(0, 16) : "";

function Metric({ value, label, note, alert }: { value?: number; label: string; note: string; alert?: boolean }) {
  return <article className={`border p-5 ${alert ? "border-[rgba(184,135,46,.65)] bg-[#fffaf0]" : "border-[rgba(22,56,49,.14)] bg-[var(--ivory)]"}`}>
    <div className="flex items-start justify-between"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[rgba(22,56,49,.66)]">{label}</p>{alert && <CircleAlert size={16} className="text-[var(--gold)]" />}</div>
    <p className="mt-5 font-display text-5xl leading-none text-[var(--forest)]">{value ?? "—"}</p>
    <p className="mt-3 text-xs leading-5 text-[rgba(23,24,21,.62)]">{note}</p>
  </article>;
}

function LogoMark() { return <div className="flex items-center gap-3"><img src="/images/logo-optimized.png" width="42" height="42" alt="Hotel De Blossom" className="h-9 w-9 object-contain" /><div><p className="font-display text-xl leading-4 text-[var(--ivory)]">De Blossom</p><p className="mt-1 font-mono text-[8px] uppercase tracking-[.19em] text-[var(--sandstone)]">Staff desk</p></div></div>; }

function SideNav({ view, setView, member, onSignOut, mobile, close }: { view: View; setView: (view: View) => void; member?: StaffMember; onSignOut: () => void; mobile?: boolean; close?: () => void }) {
  const items: Array<{ id: View; name: string; icon: typeof LayoutDashboard }> = [{ id: "overview", name: "Desk overview", icon: LayoutDashboard }, { id: "inquiries", name: "Inquiries", icon: NotebookPen }, { id: "rates", name: "Room rates", icon: IndianRupee }];
  return <aside className={`flex h-full w-[278px] flex-col bg-[var(--night)] px-5 py-6 ${mobile ? "shadow-2xl" : ""}`}>
    <div className="flex items-center justify-between"><LogoMark />{mobile && <button aria-label="Close navigation" onClick={close} className="text-[var(--ivory)]"><X /></button>}</div>
    <div className="mt-12 grid gap-1">{items.map(({ id, name, icon: Icon }) => <button key={id} onClick={() => { setView(id); close?.(); }} className={`flex min-h-11 items-center gap-3 px-3 text-left text-sm transition ${view === id ? "bg-[rgba(247,241,230,.12)] text-[var(--ivory)] shadow-[inset_2px_0_0_var(--gold)]" : "text-[rgba(255,253,248,.62)] hover:bg-[rgba(247,241,230,.06)] hover:text-[var(--ivory)]"}`}><Icon size={17} />{name}</button>)}</div>
    <div className="mt-auto border-t border-[rgba(247,241,230,.12)] pt-5"><div className="mb-4 px-3"><p className="truncate text-sm font-semibold text-[var(--ivory)]">{member?.display_name || "Loading staff…"}</p><p className="mt-1 font-mono text-[9px] uppercase tracking-[.15em] text-[var(--sandstone)]">{member?.role || "Checking access"}</p></div><button onClick={onSignOut} className="flex min-h-10 w-full items-center gap-3 px-3 text-sm text-[rgba(255,253,248,.66)] transition hover:bg-[rgba(247,241,230,.06)] hover:text-[var(--ivory)]"><LogOut size={16} /> Sign out</button></div>
  </aside>;
}

function InquiryTable({ inquiries, selectedId, onSelect, loading }: { inquiries: Inquiry[]; selectedId?: string; onSelect: (id: string) => void; loading: boolean }) {
  if (loading) return <div className="grid min-h-72 place-items-center border border-[rgba(22,56,49,.14)] bg-[var(--ivory)]"><RefreshCw className="animate-spin text-[var(--gold)]" /></div>;
  if (!inquiries.length) return <div className="grid min-h-72 place-items-center border border-dashed border-[rgba(22,56,49,.24)] bg-[var(--ivory)] p-8 text-center"><div><p className="font-display text-3xl text-[var(--forest)]">No enquiries here.</p><p className="mt-2 text-sm text-[rgba(23,24,21,.58)]">Try a different status or review the archived requests.</p></div></div>;
  return <div className="overflow-hidden border border-[rgba(22,56,49,.14)] bg-[var(--ivory)]"><div className="hidden grid-cols-[1.15fr_.75fr_.9fr_.9fr_32px] gap-4 border-b border-[rgba(22,56,49,.12)] px-5 py-3 font-mono text-[9px] uppercase tracking-[.14em] text-[rgba(22,56,49,.56)] lg:grid"><span>Guest & request</span><span>Status</span><span>Stay</span><span>Follow-up</span><span /></div>{inquiries.map((inquiry) => <button key={inquiry.id} onClick={() => onSelect(inquiry.id)} className={`grid w-full gap-3 border-b border-[rgba(22,56,49,.1)] px-5 py-4 text-left transition last:border-0 lg:grid-cols-[1.15fr_.75fr_.9fr_.9fr_32px] lg:items-center ${selectedId === inquiry.id ? "bg-[#f4ead7]" : "hover:bg-[#fbf8f0]"}`}><span><span className="block text-sm font-semibold text-[var(--forest)]">{inquiry.guest_name}</span><span className="mt-1 block font-mono text-[10px] uppercase tracking-[.09em] text-[rgba(23,24,21,.57)]">{inquiry.reference_code} · {readable(inquiry.purpose)}</span></span><span><Badge tone={statusTone(inquiry.status)}>{inquiry.status}</Badge></span><span className="text-xs text-[rgba(23,24,21,.74)]">{inquiry.check_in ? <>{compactDate(inquiry.check_in)}<span className="mx-1 text-[var(--gold)]">→</span>{compactDate(inquiry.check_out)}</> : inquiry.room_type || "Dates pending"}</span><span className={`text-xs ${inquiry.follow_up_at && new Date(inquiry.follow_up_at) < new Date() && ["new", "contacted", "provisional", "confirmed"].includes(inquiry.status) ? "font-semibold text-red-800" : "text-[rgba(23,24,21,.64)]"}`}>{dateTime(inquiry.follow_up_at)}</span><ChevronRight size={16} className="hidden text-[var(--gold)] lg:block" /></button>)}</div>;
}

function InquiryPanel({ detail, staff, onClose, onSaved }: { detail?: InquiryDetail; staff: StaffMember[]; canManage?: boolean; onClose: () => void; onSaved: () => Promise<void> }) {
  const [note, setNote] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  if (!detail) return <aside className="hidden w-[390px] border-l border-[rgba(22,56,49,.14)] bg-[var(--ivory)] xl:grid xl:place-items-center xl:p-8"><div className="text-center"><NotebookPen className="mx-auto text-[var(--gold)]" size={25} /><p className="mt-4 font-display text-3xl text-[var(--forest)]">Guest context, close at hand.</p><p className="mt-2 text-sm leading-6 text-[rgba(23,24,21,.56)]">Select an enquiry to manage its follow-up, record notes, and inspect its history.</p></div></aside>;
  const { inquiry, notes, events } = detail;
  const savePatch = async (patch: Record<string, unknown>) => { if (!supabase) return; setSaving(true); setMessage(""); try { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error("Your session has ended."); await api(data.session, `/api/staff/inquiries/${inquiry.id}`, { method: "PATCH", body: JSON.stringify(patch) }); await onSaved(); setMessage("Saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save the enquiry."); } finally { setSaving(false); } };
  const addNote = async (event: { preventDefault(): void }) => { event.preventDefault(); if (!note.trim() || !supabase) return; setSaving(true); try { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error("Your session has ended."); await api(data.session, `/api/staff/inquiries/${inquiry.id}/notes`, { method: "POST", body: JSON.stringify({ body: note }) }); setNote(""); await onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not add note."); } finally { setSaving(false); } };
  const archive = async () => { if (!supabase) return; setSaving(true); try { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error("Your session has ended."); await api(data.session, `/api/staff/inquiries/${inquiry.id}/archive?archived=${inquiry.archived_at ? "false" : "true"}`, { method: "POST" }); await onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not update archive state."); } finally { setSaving(false); } };
  return <aside className="fixed inset-y-0 right-0 z-30 flex w-full max-w-[430px] flex-col overflow-y-auto border-l border-[rgba(22,56,49,.16)] bg-[var(--ivory)] shadow-[-16px_0_48px_rgba(13,40,35,.14)] xl:static xl:shadow-none">
    <header className="sticky top-0 z-10 flex items-center justify-between border-b border-[rgba(22,56,49,.13)] bg-[var(--ivory)] px-6 py-5"><div><p className="font-mono text-[10px] uppercase tracking-[.14em] text-[var(--gold)]">{inquiry.reference_code}</p><h2 className="mt-1 font-display text-3xl leading-none text-[var(--forest)]">{inquiry.guest_name}</h2></div><button aria-label="Close enquiry" onClick={onClose} className="grid h-10 w-10 place-items-center text-[var(--forest)] hover:bg-[rgba(22,56,49,.07)]"><X size={20} /></button></header>
    <div className="space-y-7 p-6"><section className="grid grid-cols-2 gap-x-5 gap-y-4 border-b border-[rgba(22,56,49,.12)] pb-6"><div><p className="font-mono text-[9px] uppercase tracking-[.13em] text-[rgba(22,56,49,.56)]">Requested</p><p className="mt-1 text-sm font-semibold text-[var(--forest)]">{readable(inquiry.purpose)}</p></div><div><p className="font-mono text-[9px] uppercase tracking-[.13em] text-[rgba(22,56,49,.56)]">Party</p><p className="mt-1 text-sm font-semibold text-[var(--forest)]">{inquiry.guests} guest{inquiry.guests === 1 ? "" : "s"}</p></div><div><p className="font-mono text-[9px] uppercase tracking-[.13em] text-[rgba(22,56,49,.56)]">Stay</p><p className="mt-1 text-sm font-semibold text-[var(--forest)]">{inquiry.check_in ? `${compactDate(inquiry.check_in)} — ${compactDate(inquiry.check_out)}` : "To be confirmed"}</p></div><div><p className="font-mono text-[9px] uppercase tracking-[.13em] text-[rgba(22,56,49,.56)]">Room preference</p><p className="mt-1 text-sm font-semibold text-[var(--forest)]">{inquiry.room_type || "Not specified"}</p></div></section>
      <section><p className="font-mono text-[9px] uppercase tracking-[.15em] text-[rgba(22,56,49,.58)]">Reach the guest</p><div className="mt-3 flex gap-2"><a href={`tel:${inquiry.phone}`} className="min-h-10 flex-1 border border-[rgba(22,56,49,.18)] px-3 py-2 text-center text-sm font-semibold text-[var(--forest)] hover:bg-[rgba(22,56,49,.06)]">Call</a>{inquiry.email && <a href={`mailto:${inquiry.email}`} className="min-h-10 flex-1 border border-[rgba(22,56,49,.18)] px-3 py-2 text-center text-sm font-semibold text-[var(--forest)] hover:bg-[rgba(22,56,49,.06)]">Email</a>}</div>{inquiry.message && <p className="mt-3 border-l-2 border-[var(--gold)] bg-[#fbf6ea] p-3 text-sm leading-6 text-[rgba(23,24,21,.75)]">{inquiry.message}</p>}</section>
      <section className="border-y border-[rgba(22,56,49,.12)] py-6"><div className="flex items-center justify-between"><p className="font-mono text-[9px] uppercase tracking-[.15em] text-[rgba(22,56,49,.58)]">Follow-up controls</p>{saving && <RefreshCw size={14} className="animate-spin text-[var(--gold)]" />}</div><div className="mt-4 grid gap-3"><label className="grid gap-1.5 text-xs font-semibold text-[var(--forest)]">Status<select value={inquiry.status} disabled={saving} onChange={(e) => void savePatch({ status: e.target.value })} className="min-h-10 border border-[rgba(22,56,49,.18)] bg-white px-3 text-sm font-normal outline-none focus:border-[var(--gold)]">{statuses.map((status) => <option key={status} value={status}>{readable(status)}</option>)}</select></label><label className="grid gap-1.5 text-xs font-semibold text-[var(--forest)]">Assigned to<select value={inquiry.assigned_to || ""} disabled={saving} onChange={(e) => void savePatch({ assignedTo: e.target.value || null })} className="min-h-10 border border-[rgba(22,56,49,.18)] bg-white px-3 text-sm font-normal outline-none focus:border-[var(--gold)]"><option value="">Unassigned</option>{staff.map((person) => <option value={person.user_id} key={person.user_id}>{person.display_name} · {person.role}</option>)}</select></label><label className="grid gap-1.5 text-xs font-semibold text-[var(--forest)]">Follow-up<input type="datetime-local" value={localInput(inquiry.follow_up_at)} disabled={saving} onChange={(e) => void savePatch({ followUpAt: e.target.value ? new Date(e.target.value).toISOString() : null })} className="min-h-10 border border-[rgba(22,56,49,.18)] bg-white px-3 text-sm font-normal outline-none focus:border-[var(--gold)]" /></label></div>{(inquiry.status === "closed" || inquiry.status === "cancelled") && <Button variant="subtle" size="sm" onClick={() => void archive()} disabled={saving} className="mt-4">{inquiry.archived_at ? "Restore request" : <><Archive size={13} /> Archive request</>}</Button>}{message && <p role="status" className="mt-3 text-xs text-[var(--forest)]">{message}</p>}</section>
      <section><p className="font-mono text-[9px] uppercase tracking-[.15em] text-[rgba(22,56,49,.58)]">Internal notes</p><form className="mt-3" onSubmit={addNote}><textarea value={note} onChange={(e) => setNote(e.target.value)} maxLength={4000} placeholder="Leave a useful handover note…" className="min-h-20 w-full resize-y border border-[rgba(22,56,49,.18)] bg-white p-3 text-sm outline-none focus:border-[var(--gold)]" /><Button type="submit" size="sm" variant="subtle" disabled={saving || !note.trim()} className="mt-2">Add note</Button></form><div className="mt-4 space-y-3">{notes.map((item) => <article key={item.id} className="border-l border-[var(--gold)] bg-[#fbf8f0] p-3"><p className="text-sm leading-6 text-[rgba(23,24,21,.78)]">{item.body}</p><p className="mt-2 font-mono text-[9px] uppercase tracking-[.11em] text-[rgba(22,56,49,.55)]">{dateTime(item.created_at)}</p></article>)}</div></section>
      <section><p className="font-mono text-[9px] uppercase tracking-[.15em] text-[rgba(22,56,49,.58)]">Audit trail</p><ol className="mt-4 space-y-3 border-l border-[rgba(184,135,46,.55)] pl-4">{events.map((event) => <li key={event.id}><p className="text-xs font-semibold capitalize text-[var(--forest)]">{readable(event.event_type)}{event.from_status && event.to_status ? ` · ${event.from_status} → ${event.to_status}` : ""}</p><p className="mt-1 font-mono text-[9px] uppercase tracking-[.1em] text-[rgba(22,56,49,.54)]">{dateTime(event.created_at)}</p></li>)}</ol></section>
    </div>
  </aside>;
}

export default function StaffApp() {
  const [view, setView] = useState<View>("overview"); const [sessionReady, setSessionReady] = useState(false); const [summary, setSummary] = useState<Summary>(); const [staff, setStaff] = useState<StaffMember[]>([]); const [rates, setRates] = useState<Rate[]>([]); const [inquiries, setInquiries] = useState<Inquiry[]>([]); const [selected, setSelected] = useState<InquiryDetail>(); const [filter, setFilter] = useState<InquiryStatus | "all">("all"); const [archived, setArchived] = useState(false); const [nextBefore, setNextBefore] = useState<string | null>(null); const [previous, setPreviousState] = useState<string[]>([]); const [userId, setUserId] = useState<string>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [mobileNav, setMobileNav] = useState(false); const [editingRate, setEditingRate] = useState<string | null>(null); const [rateValue, setRateValue] = useState("");
  const activeMember = useMemo(() => staff.find((person) => person.user_id === userId), [staff, userId]);
  const pseudoMember = activeMember;
  const currentStaff = activeMember;
  const activeCursor = useRef<string | undefined>(undefined);
  const setPrevious = (value: string[] | ((items: string[]) => string[])) => setPreviousState((items) => {
    const next = typeof value === "function" ? value(items) : value;
    if (next.length === items.length + 1 && next.at(-1) === "") return [...next.slice(0, -1), activeCursor.current || ""];
    return next;
  });
  const refresh = useCallback(async (before?: string, desiredStatus = filter, archivedView = archived) => { if (!supabase) return; const { data } = await supabase.auth.getSession(); if (!data.session) { window.location.replace("/staff/login?next=/staff"); return; } setLoading(true); setError(""); try { const params = new URLSearchParams({ limit: "25" }); if (desiredStatus !== "all") params.set("status", desiredStatus); if (before) params.set("before", before); if (archivedView) params.set("archived", "true"); const [list, dashboard, team, roomRates] = await Promise.all([api<{ data: Inquiry[]; nextBefore: string | null }>(data.session, `/api/staff/inquiries?${params}`), api<{ data: Summary }>(data.session, "/api/staff/summary"), api<{ data: StaffMember[] }>(data.session, "/api/staff/staff"), api<{ data: Rate[] }>(data.session, "/api/staff/rates")]); activeCursor.current = before; setInquiries(list.data); setNextBefore(list.nextBefore); setSummary(dashboard.data); setStaff(team.data); setRates(roomRates.data); setUserId(data.session.user.id); setSessionReady(true); } catch (reason) { const message = reason instanceof Error ? reason.message : "Could not load the staff desk."; if (/session|sign-in|access/i.test(message)) window.location.replace("/staff/login?next=/staff"); else setError(message); } finally { setLoading(false); } }, [archived, filter]);
  useEffect(() => { if (!configured || !supabase) { setError("Missing public Supabase configuration."); setLoading(false); return; } void refresh(); }, [refresh]);
  const openInquiry = async (id: string) => { if (!supabase) return; try { const { data } = await supabase.auth.getSession(); if (!data.session) return; const result = await api<{ data: InquiryDetail }>(data.session, `/api/staff/inquiries/${id}`); setSelected(result.data); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not open enquiry."); } };
  const reloadSelected = async () => { if (!selected) return; await refresh(); await openInquiry(selected.inquiry.id); };
  const applyFilter = (value: InquiryStatus | "all") => { setFilter(value); setPrevious([]); setSelected(undefined); void refresh(undefined, value, archived); };
  const changeArchive = (value: boolean) => { setArchived(value); setPrevious([]); setSelected(undefined); void refresh(undefined, filter, value); };
  const saveRate = async (rate: Rate) => { if (!supabase) return; const amount = Number(rateValue); if (!Number.isInteger(amount) || amount < 0) { setError("Enter a whole, non-negative INR amount."); return; } try { const { data } = await supabase.auth.getSession(); if (!data.session) throw new Error("Your session has ended."); await api(data.session, `/api/staff/rates/${rate.id}`, { method: "PATCH", body: JSON.stringify({ baseNightlyInr: amount }) }); setEditingRate(null); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not update the room rate."); } };
  const signOut = async () => { await supabase?.auth.signOut(); window.location.assign("/staff/login"); };
  if (!sessionReady && loading) return <main className="grid min-h-screen place-items-center bg-[var(--champagne)]"><div className="text-center"><img src="/images/logo-optimized.png" width="56" height="56" alt="" className="mx-auto h-14 w-14 animate-pulse object-contain" /><p className="mt-5 font-mono text-[10px] uppercase tracking-[.18em] text-[var(--forest)]">Opening the staff desk</p></div></main>;
  return <main className="min-h-screen bg-[var(--champagne)] text-[var(--charcoal)] lg:flex"><div className="hidden lg:fixed lg:inset-y-0 lg:block"><SideNav view={view} setView={setView} member={pseudoMember} onSignOut={() => void signOut()} /></div>{mobileNav && <div className="fixed inset-0 z-40 bg-[rgba(13,40,35,.52)] lg:hidden"><SideNav mobile view={view} setView={setView} member={pseudoMember} onSignOut={() => void signOut()} close={() => setMobileNav(false)} /></div>}<section className="min-w-0 flex-1 lg:ml-[278px]"><header className="flex min-h-[72px] items-center justify-between border-b border-[rgba(22,56,49,.13)] bg-[rgba(255,253,248,.8)] px-5 backdrop-blur-sm sm:px-8"><div className="flex items-center gap-3"><button className="grid h-10 w-10 place-items-center text-[var(--forest)] lg:hidden" onClick={() => setMobileNav(true)} aria-label="Open navigation"><Menu /></button><div><p className="font-mono text-[9px] uppercase tracking-[.16em] text-[var(--gold)]">Front desk operations</p><p className="font-display text-2xl leading-6 text-[var(--forest)]">{view === "overview" ? "Good day, team." : view === "inquiries" ? "Enquiry book" : "Room rate ledger"}</p></div></div><div className="flex items-center gap-2"><p className="hidden font-mono text-[10px] uppercase tracking-[.12em] text-[rgba(22,56,49,.6)] sm:block">{new Intl.DateTimeFormat("en-IN", { weekday: "short", day: "2-digit", month: "short" }).format(new Date())}</p><Button size="icon" variant="ghost" onClick={() => void refresh()} aria-label="Refresh desk"><RefreshCw size={17} /></Button></div></header><div className="mx-auto max-w-[1580px] p-5 sm:p-8">{error && <div role="alert" className="mb-6 flex items-start justify-between gap-4 border-l-2 border-red-700 bg-red-50 px-4 py-3 text-sm text-red-900"><span>{error}</span><button onClick={() => setError("")} aria-label="Dismiss error"><X size={17} /></button></div>}
    {view === "overview" && <div className="reveal"><div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[rgba(22,56,49,.6)]">Today’s reception readout</p><h1 className="mt-2 font-display text-4xl text-[var(--forest)] sm:text-5xl">Nothing important <em>gets lost.</em></h1></div><Button variant="gold" onClick={() => setView("inquiries")}><BellRing size={16} /> Review enquiries</Button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric value={summary?.new} label="New enquiries" note="Awaiting their first considered response." /><Metric value={summary?.unassignedNew} label="Unassigned" note="New guest requests without an owner." alert={(summary?.unassignedNew || 0) > 0} /><Metric value={summary?.overdueFollowups} label="Overdue follow-ups" note="Active enquiries past their promised callback." alert={(summary?.overdueFollowups || 0) > 0} /><Metric value={summary?.dueToday} label="Due today" note="Follow-ups scheduled before day close." /></div><div className="mt-8 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="border border-[rgba(22,56,49,.14)] bg-[var(--ivory)]"><div className="flex items-center justify-between border-b border-[rgba(22,56,49,.12)] px-5 py-4"><div><p className="font-mono text-[9px] uppercase tracking-[.14em] text-[rgba(22,56,49,.58)]">Newest arrivals</p><h2 className="mt-1 font-display text-2xl text-[var(--forest)]">The enquiry desk</h2></div><button onClick={() => setView("inquiries")} className="text-xs font-bold text-[var(--forest)] hover:text-[var(--gold)]">See all</button></div><InquiryTable inquiries={inquiries.slice(0, 5)} loading={loading} onSelect={(id) => { setView("inquiries"); void openInquiry(id); }} /></section><section className="border border-[rgba(22,56,49,.14)] bg-[var(--forest)] p-6 text-[var(--ivory)]"><Clock3 size={20} className="text-[var(--sandstone)]" /><p className="mt-8 font-mono text-[10px] uppercase tracking-[.16em] text-[var(--sandstone)]">Response rhythm</p><h2 className="mt-2 font-display text-4xl leading-[.92]">Warmth is in the follow-through.</h2><p className="mt-5 text-sm leading-6 text-[rgba(255,253,248,.72)]">Prioritise unassigned new enquiries, then use follow-up dates to make every promise visible to the team.</p><div className="mt-8 border-t border-[rgba(255,253,248,.18)] pt-4 font-mono text-[10px] uppercase tracking-[.12em] text-[var(--sandstone)]">Operational, not automated</div></section></div></div>}
    {view === "inquiries" && <div className="reveal"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[rgba(22,56,49,.6)]">Guest requests</p><h1 className="mt-2 font-display text-4xl text-[var(--forest)] sm:text-5xl">Every stay starts <em>somewhere.</em></h1></div><label className="flex min-h-10 items-center gap-2 border border-[rgba(22,56,49,.16)] bg-[var(--ivory)] px-3 text-xs font-semibold text-[var(--forest)]"><Archive size={14} /><input type="checkbox" checked={archived} onChange={(e) => changeArchive(e.target.checked)} /> Archived only</label></div><div className="mb-5 flex flex-wrap gap-2"><span className="mr-1 flex items-center font-mono text-[9px] uppercase tracking-[.13em] text-[rgba(22,56,49,.58)]"><SlidersHorizontal size={13} className="mr-2" /> Filter</span>{(["all", ...statuses] as const).map((status) => <button key={status} onClick={() => applyFilter(status)} className={`min-h-8 border px-3 text-xs font-semibold capitalize transition ${filter === status ? "border-[var(--forest)] bg-[var(--forest)] text-[var(--ivory)]" : "border-[rgba(22,56,49,.16)] bg-[var(--ivory)] text-[var(--forest)] hover:border-[var(--gold)]"}`}>{status}</button>)}</div><div className="flex min-w-0 gap-5"><section className="min-w-0 flex-1"><InquiryTable inquiries={inquiries} selectedId={selected?.inquiry.id} loading={loading} onSelect={(id) => void openInquiry(id)} /><div className="mt-4 flex items-center justify-between"><Button variant="subtle" size="sm" disabled={!previous.length || loading} onClick={() => { const back = previous.at(-1); setPrevious((items) => items.slice(0, -1)); void refresh(back); }}><ArrowLeft size={14} /> Previous</Button><p className="font-mono text-[9px] uppercase tracking-[.13em] text-[rgba(22,56,49,.58)]">Keyset pagination</p><Button variant="subtle" size="sm" disabled={!nextBefore || loading} onClick={() => { if (nextBefore) { setPrevious((items) => [...items, ""]); void refresh(nextBefore); } }}>Next <ArrowRight size={14} /></Button></div></section>{selected && <InquiryPanel detail={selected} staff={staff} canManage={Boolean(currentStaff)} onClose={() => setSelected(undefined)} onSaved={reloadSelected} />}</div></div>}
    {view === "rates" && <div className="reveal"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[rgba(22,56,49,.6)]">Published starting rates</p><h1 className="mt-2 font-display text-4xl text-[var(--forest)] sm:text-5xl">The room rate <em>ledger.</em></h1><p className="mt-3 max-w-xl text-sm leading-6 text-[rgba(23,24,21,.63)]">Base nightly prices in INR. Changes are restricted to managers and administrators and never imply live availability.</p></div><div className="flex items-center gap-2 border border-[rgba(22,56,49,.15)] bg-[var(--ivory)] px-3 py-2 text-xs text-[rgba(23,24,21,.62)]"><UsersRound size={15} className="text-[var(--gold)]" /> Manager approval required</div></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rates.map((rate) => <article key={rate.id} className="border border-[rgba(22,56,49,.14)] bg-[var(--ivory)] p-5"><p className="font-mono text-[10px] uppercase tracking-[.15em] text-[var(--gold)]">{rate.is_active ? "Active rate" : "Inactive"}</p><h2 className="mt-3 font-display text-3xl text-[var(--forest)]">{rate.room_type}</h2>{editingRate === rate.id ? <div className="mt-6 flex gap-2"><label className="flex min-h-11 flex-1 items-center border border-[var(--gold)] bg-white px-3"><span className="mr-1 text-sm text-[rgba(23,24,21,.55)]">₹</span><input autoFocus type="number" min="0" step="1" value={rateValue} onChange={(e) => setRateValue(e.target.value)} className="w-full bg-transparent text-xl font-semibold outline-none" /></label><Button size="icon" variant="gold" aria-label="Save rate" onClick={() => void saveRate(rate)}><Check size={17} /></Button><Button size="icon" variant="subtle" aria-label="Cancel rate edit" onClick={() => setEditingRate(null)}><X size={17} /></Button></div> : <><p className="mt-6 font-display text-5xl leading-none text-[var(--forest)]">₹{new Intl.NumberFormat("en-IN").format(rate.base_nightly_inr)}</p><p className="mt-2 font-mono text-[9px] uppercase tracking-[.12em] text-[rgba(22,56,49,.54)]">Base nightly rate · updated {compactDate(rate.updated_at)}</p><Button className="mt-6" variant="subtle" size="sm" onClick={() => { setEditingRate(rate.id); setRateValue(String(rate.base_nightly_inr)); }}>Adjust price</Button></>}</article>)}{!rates.length && <p className="col-span-full border border-dashed border-[rgba(22,56,49,.25)] p-10 text-center text-sm text-[rgba(23,24,21,.6)]">No room rates are configured yet. Add the approved room types through the database migration before publishing prices.</p>}</div></div>}
  </div></section></main>;
}
